import Navbar from "@/components/my-components/Navbar";
import Footer from "@/components/my-components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col min-h-screen`}>
        <Navbar />
        <section className="p-4 bg-slate-200 flex-grow">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
